#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"

#include "sensorarrayTypes.h"

typedef enum {
    SENSORARRAY_RECOVERY_FAIL_ACTION_IDLE = 0,
    SENSORARRAY_RECOVERY_FAIL_ACTION_RESTART,
    SENSORARRAY_RECOVERY_FAIL_ACTION_PANIC,
} sensorarrayRecoveryFailAction_t;

typedef enum {
    SENSORARRAY_RECOVERY_CAUSE_NONE = 0,
    SENSORARRAY_RECOVERY_CAUSE_EXPLICIT_FATAL,
    SENSORARRAY_RECOVERY_CAUSE_PROGRESS_STALL,
} sensorarrayRecoveryCause_t;

typedef enum {
    SENSORARRAY_RECOVERY_STAGE_UNKNOWN = 0,
    SENSORARRAY_RECOVERY_STAGE_BOOT,
    SENSORARRAY_RECOVERY_STAGE_APP_INIT,
    SENSORARRAY_RECOVERY_STAGE_FDC_INIT_BEGIN,
    SENSORARRAY_RECOVERY_STAGE_FDC_INIT_END,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_ROW_ENTER,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_ROW_EXIT,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_SELA_ENTER,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_SELA_EXIT,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_SELB_ENTER,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_SELB_EXIT,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_SW_ENTER,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_SW_EXIT,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_VERIFY_ENTER,
    SENSORARRAY_RECOVERY_STAGE_ROUTE_VERIFY_EXIT,
    SENSORARRAY_RECOVERY_STAGE_SWEEP_CANDIDATE_BEGIN,
    SENSORARRAY_RECOVERY_STAGE_SWEEP_CANDIDATE_END,
    SENSORARRAY_RECOVERY_STAGE_LOCKED_SAMPLE_BEGIN,
    SENSORARRAY_RECOVERY_STAGE_LOCKED_SAMPLE_END,
    SENSORARRAY_RECOVERY_STAGE_RECOVERY_BEGIN,
    SENSORARRAY_RECOVERY_STAGE_RESTART_PENDING,
} sensorarrayRecoveryStage_t;

typedef enum {
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_FDC_INIT_BEGIN = 0,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_FDC_INIT_OK,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_APPLIED,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_STEP_BEGIN,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SNAPSHOT_DONE,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_WARNING,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SWEEP_CANDIDATE_BEGIN,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SWEEP_KEYREGS_BEGIN,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SWEEP_KEYREGS_DONE,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SWEEP_SAMPLE_BEGIN,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SWEEP_SAMPLE_DONE,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SWEEP_RECOVER_BEGIN,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_SWEEP_RECOVER_DONE,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_TERMINAL_FAULT,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_ROW_ENTER,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_ROW_EXIT,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_SELA_ENTER,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_SELA_EXIT,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_SELB_ENTER,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_SELB_EXIT,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_SW_ENTER,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_SW_EXIT,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_VERIFY_ENTER,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_ROUTE_VERIFY_EXIT,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_RECOVERY_BEGIN,
    SENSORARRAY_RECOVERY_CHECKPOINT_EVENT_RESTART_PENDING,
} sensorarrayRecoveryCheckpointEvent_t;

void sensorarrayRecoveryInit(sensorarrayDebugMode_t mode);
void sensorarrayRecoveryLogBootInfo(void);
bool sensorarrayRecoveryIsS5d5Mode(void);

sensorarrayRecoveryFailAction_t sensorarrayRecoveryFailAction(void);
const char *sensorarrayRecoveryFailActionName(sensorarrayRecoveryFailAction_t action);
const char *sensorarrayRecoveryCauseName(sensorarrayRecoveryCause_t cause);
const char *sensorarrayRecoveryStageName(sensorarrayRecoveryStage_t stage);

void sensorarrayRecoveryKick(sensorarrayRecoveryStage_t stage, uint8_t sColumn, uint8_t dLine);
void sensorarrayRecoveryKickAlive(void);
void sensorarrayRecoveryEmitCheckpoint(sensorarrayRecoveryCheckpointEvent_t event);

void sensorarrayRecoveryHandleFatal(const char *reason,
                                    esp_err_t err,
                                    sensorarrayRecoveryStage_t stage,
                                    uint8_t sColumn,
                                    uint8_t dLine);
void sensorarrayRecoveryControlledIdle(const char *reason, uint32_t heartbeatMs);

void sensorarrayRecoveryTaskWdtRegisterCurrentTask(const char *taskTag);
void sensorarrayRecoveryTaskWdtReset(void);
void sensorarrayRecoveryTaskWdtDeleteCurrentTask(void);
